--------------------------------------------------------------------------------
-- PaySQL :: V1.0.0 :: Reference / lookup tables
-- Foundational, slowly-changing data referenced across the schema.
--------------------------------------------------------------------------------

-- Currencies (multi-currency support) -----------------------------------------
CREATE TABLE currency (
    currency_code   VARCHAR2(3)   NOT NULL,
    currency_name   VARCHAR2(60)  NOT NULL,
    symbol          VARCHAR2(6),
    CONSTRAINT pk_currency PRIMARY KEY (currency_code)
);
COMMENT ON TABLE currency IS 'ISO 4217 currencies usable for salaries, funds and payments.';

-- Departments -----------------------------------------------------------------
CREATE TABLE department (
    department_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code            VARCHAR2(20)  NOT NULL,
    name            VARCHAR2(100) NOT NULL,
    created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_department        PRIMARY KEY (department_id),
    CONSTRAINT uq_department_code   UNIQUE (code)
);
COMMENT ON TABLE department IS 'Organizational departments employees belong to.';

-- Job grades / pay bands ------------------------------------------------------
CREATE TABLE job_grade (
    job_grade_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code            VARCHAR2(20)  NOT NULL,
    name            VARCHAR2(100) NOT NULL,
    min_salary      NUMBER(14,2),
    max_salary      NUMBER(14,2),
    CONSTRAINT pk_job_grade         PRIMARY KEY (job_grade_id),
    CONSTRAINT uq_job_grade_code    UNIQUE (code),
    CONSTRAINT ck_job_grade_band    CHECK (max_salary IS NULL OR min_salary IS NULL OR max_salary >= min_salary)
);
COMMENT ON TABLE job_grade IS 'Job grades / pay bands with optional salary ranges.';

-- Pay components (the heart of component-based compensation) -------------------
CREATE TABLE pay_component (
    pay_component_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code                VARCHAR2(30)  NOT NULL,
    name                VARCHAR2(100) NOT NULL,
    component_type      VARCHAR2(10)  NOT NULL,
    calculation_method  VARCHAR2(20)  DEFAULT 'FIXED' NOT NULL,
    default_rate        NUMBER(7,4),
    is_taxable          NUMBER(1)     DEFAULT 0 NOT NULL,
    display_order       NUMBER(4)     DEFAULT 100 NOT NULL,
    is_active           NUMBER(1)     DEFAULT 1 NOT NULL,
    CONSTRAINT pk_pay_component          PRIMARY KEY (pay_component_id),
    CONSTRAINT uq_pay_component_code     UNIQUE (code),
    CONSTRAINT ck_pay_component_type     CHECK (component_type IN ('EARNING','DEDUCTION')),
    CONSTRAINT ck_pay_component_method   CHECK (calculation_method IN ('FIXED','PERCENT_OF_BASIC','FORMULA')),
    CONSTRAINT ck_pay_component_taxable  CHECK (is_taxable IN (0,1)),
    CONSTRAINT ck_pay_component_active   CHECK (is_active IN (0,1))
);
COMMENT ON TABLE pay_component IS 'Earning/deduction definitions. Compensation is data, not hardcoded columns.';
COMMENT ON COLUMN pay_component.component_type IS 'EARNING adds to gross; DEDUCTION subtracts from gross.';
COMMENT ON COLUMN pay_component.calculation_method IS 'FIXED amount, PERCENT_OF_BASIC, or FORMULA (engine-evaluated).';

-- Leave types -----------------------------------------------------------------
CREATE TABLE leave_type (
    leave_type_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code            VARCHAR2(20)  NOT NULL,
    name            VARCHAR2(100) NOT NULL,
    is_paid         NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_leave_type        PRIMARY KEY (leave_type_id),
    CONSTRAINT uq_leave_type_code   UNIQUE (code),
    CONSTRAINT ck_leave_type_paid   CHECK (is_paid IN (0,1))
);
COMMENT ON TABLE leave_type IS 'Categories of leave; unpaid leave drives loss-of-pay.';

-- Tax slabs (configurable, country-aware, effective-dated) ---------------------
CREATE TABLE tax_slab (
    tax_slab_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    country_code    VARCHAR2(2)   NOT NULL,
    lower_bound     NUMBER(14,2)  NOT NULL,
    upper_bound     NUMBER(14,2),
    rate            NUMBER(5,4)   NOT NULL,
    effective_from  DATE          NOT NULL,
    effective_to    DATE,
    CONSTRAINT pk_tax_slab         PRIMARY KEY (tax_slab_id),
    CONSTRAINT ck_tax_slab_rate    CHECK (rate >= 0 AND rate <= 1),
    CONSTRAINT ck_tax_slab_bounds  CHECK (upper_bound IS NULL OR upper_bound > lower_bound)
);
COMMENT ON TABLE tax_slab IS 'Progressive tax brackets by country; rate is a fraction (0.10 = 10%).';
