--------------------------------------------------------------------------------
-- PaySQL :: V1.1.0 :: Core HR
-- Employees and their organizational placement.
--------------------------------------------------------------------------------

CREATE TABLE employee (
    employee_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_code       VARCHAR2(20)  NOT NULL,
    first_name          VARCHAR2(60)  NOT NULL,
    last_name           VARCHAR2(60)  NOT NULL,
    gender              VARCHAR2(12)  DEFAULT 'UNDISCLOSED' NOT NULL,
    email               VARCHAR2(255) NOT NULL,
    phone               VARCHAR2(30),
    department_id       NUMBER,
    job_grade_id        NUMBER,
    currency_code       VARCHAR2(3)   DEFAULT 'USD' NOT NULL,
    hire_date           DATE          NOT NULL,
    termination_date    DATE,
    employment_status   VARCHAR2(12)  DEFAULT 'ACTIVE' NOT NULL,
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_employee              PRIMARY KEY (employee_id),
    CONSTRAINT uq_employee_code         UNIQUE (employee_code),
    CONSTRAINT uq_employee_email        UNIQUE (email),
    CONSTRAINT fk_employee_department   FOREIGN KEY (department_id) REFERENCES department (department_id),
    CONSTRAINT fk_employee_job_grade    FOREIGN KEY (job_grade_id)  REFERENCES job_grade (job_grade_id),
    CONSTRAINT fk_employee_currency     FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
    CONSTRAINT ck_employee_gender       CHECK (gender IN ('MALE','FEMALE','OTHER','UNDISCLOSED')),
    CONSTRAINT ck_employee_status       CHECK (employment_status IN ('ACTIVE','ON_LEAVE','TERMINATED')),
    CONSTRAINT ck_employee_term_date    CHECK (termination_date IS NULL OR termination_date >= hire_date)
);
COMMENT ON TABLE employee IS 'Employee master record. Email/code are proper-length and unique.';
COMMENT ON COLUMN employee.hire_date IS 'Real DATE (previously stored as free-text VARCHAR2).';

CREATE INDEX ix_employee_department ON employee (department_id);
CREATE INDEX ix_employee_job_grade  ON employee (job_grade_id);
