--------------------------------------------------------------------------------
-- PaySQL :: V1.2.0 :: Compensation
-- Effective-dated salary with component-based structure.
--------------------------------------------------------------------------------

-- Effective-dated salary header: one row per salary revision per employee.
CREATE TABLE employee_salary (
    employee_salary_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_id         NUMBER        NOT NULL,
    valid_from          DATE          NOT NULL,
    valid_to            DATE,
    currency_code       VARCHAR2(3)   NOT NULL,
    note                VARCHAR2(400),
    created_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_employee_salary       PRIMARY KEY (employee_salary_id),
    CONSTRAINT fk_emp_salary_employee   FOREIGN KEY (employee_id)   REFERENCES employee (employee_id),
    CONSTRAINT fk_emp_salary_currency   FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
    CONSTRAINT uq_emp_salary_from       UNIQUE (employee_id, valid_from),
    CONSTRAINT ck_emp_salary_period     CHECK (valid_to IS NULL OR valid_to >= valid_from)
);
COMMENT ON TABLE employee_salary IS 'Effective-dated salary revisions. valid_to NULL = currently active. A raise never destroys history.';

CREATE INDEX ix_emp_salary_employee ON employee_salary (employee_id);

-- Component lines of a salary revision (basic, allowances, standing deductions).
CREATE TABLE employee_salary_component (
    esc_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_salary_id  NUMBER        NOT NULL,
    pay_component_id    NUMBER        NOT NULL,
    amount              NUMBER(14,2),
    rate                NUMBER(7,4),
    CONSTRAINT pk_emp_salary_comp       PRIMARY KEY (esc_id),
    CONSTRAINT fk_esc_salary            FOREIGN KEY (employee_salary_id) REFERENCES employee_salary (employee_salary_id),
    CONSTRAINT fk_esc_component         FOREIGN KEY (pay_component_id)   REFERENCES pay_component (pay_component_id),
    CONSTRAINT uq_esc_salary_component  UNIQUE (employee_salary_id, pay_component_id),
    CONSTRAINT ck_esc_amount_or_rate    CHECK (amount IS NOT NULL OR rate IS NOT NULL)
);
COMMENT ON TABLE employee_salary_component IS 'Per-revision component values: a fixed amount and/or a rate (for percentage methods).';
