--------------------------------------------------------------------------------
-- PaySQL :: V1.3.0 :: Payroll
-- Pay periods, pay runs, payslips, payments, funds, leave and loans.
--------------------------------------------------------------------------------

-- Pay periods -----------------------------------------------------------------
CREATE TABLE pay_period (
    pay_period_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    period_code     VARCHAR2(20)  NOT NULL,
    period_name     VARCHAR2(60)  NOT NULL,
    start_date      DATE          NOT NULL,
    end_date        DATE          NOT NULL,
    pay_date        DATE          NOT NULL,
    status          VARCHAR2(10)  DEFAULT 'OPEN' NOT NULL,
    CONSTRAINT pk_pay_period        PRIMARY KEY (pay_period_id),
    CONSTRAINT uq_pay_period_code   UNIQUE (period_code),
    CONSTRAINT ck_pay_period_status CHECK (status IN ('OPEN','LOCKED','CLOSED')),
    CONSTRAINT ck_pay_period_dates  CHECK (end_date >= start_date)
);
COMMENT ON TABLE pay_period IS 'A payroll period (e.g. a calendar month) with dates replacing the old free-text month strings.';

-- Pay runs with a real lifecycle ----------------------------------------------
CREATE TABLE pay_run (
    pay_run_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    pay_period_id   NUMBER        NOT NULL,
    status          VARCHAR2(12)  DEFAULT 'DRAFT' NOT NULL,
    run_at          TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    approved_by     VARCHAR2(60),
    approved_at     TIMESTAMP,
    note            VARCHAR2(400),
    CONSTRAINT pk_pay_run           PRIMARY KEY (pay_run_id),
    CONSTRAINT fk_pay_run_period    FOREIGN KEY (pay_period_id) REFERENCES pay_period (pay_period_id),
    CONSTRAINT ck_pay_run_status    CHECK (status IN ('DRAFT','CALCULATED','APPROVED','POSTED','PAID','CLOSED'))
);
COMMENT ON TABLE pay_run IS 'A payroll execution for a period. Lifecycle: DRAFT -> CALCULATED -> APPROVED -> POSTED -> PAID -> CLOSED.';

CREATE INDEX ix_pay_run_period ON pay_run (pay_period_id);

-- Payslips (header per employee per run) --------------------------------------
CREATE TABLE payslip (
    payslip_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    pay_run_id          NUMBER        NOT NULL,
    employee_id         NUMBER        NOT NULL,
    currency_code       VARCHAR2(3)   NOT NULL,
    gross_earnings      NUMBER(14,2)  DEFAULT 0 NOT NULL,
    total_deductions    NUMBER(14,2)  DEFAULT 0 NOT NULL,
    net_pay             NUMBER(14,2)  DEFAULT 0 NOT NULL,
    leave_days          NUMBER(5,1)   DEFAULT 0 NOT NULL,
    status              VARCHAR2(10)  DEFAULT 'DRAFT' NOT NULL,
    CONSTRAINT pk_payslip               PRIMARY KEY (payslip_id),
    CONSTRAINT fk_payslip_run           FOREIGN KEY (pay_run_id)    REFERENCES pay_run (pay_run_id),
    CONSTRAINT fk_payslip_employee      FOREIGN KEY (employee_id)   REFERENCES employee (employee_id),
    CONSTRAINT fk_payslip_currency      FOREIGN KEY (currency_code) REFERENCES currency (currency_code),
    CONSTRAINT uq_payslip_run_employee  UNIQUE (pay_run_id, employee_id),
    CONSTRAINT ck_payslip_status        CHECK (status IN ('DRAFT','FINAL'))
);
COMMENT ON TABLE payslip IS 'Computed pay for one employee in one pay run.';

-- Payslip lines (one per component) -------------------------------------------
CREATE TABLE payslip_line (
    payslip_line_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    payslip_id          NUMBER        NOT NULL,
    pay_component_id    NUMBER        NOT NULL,
    amount              NUMBER(14,2)  NOT NULL,
    CONSTRAINT pk_payslip_line          PRIMARY KEY (payslip_line_id),
    CONSTRAINT fk_payslip_line_slip     FOREIGN KEY (payslip_id)       REFERENCES payslip (payslip_id),
    CONSTRAINT fk_payslip_line_comp     FOREIGN KEY (pay_component_id) REFERENCES pay_component (pay_component_id),
    CONSTRAINT uq_payslip_line          UNIQUE (payslip_id, pay_component_id)
);
COMMENT ON TABLE payslip_line IS 'Line-level breakdown of a payslip by pay component.';

-- Company funds (source of salary payments) -----------------------------------
CREATE TABLE fund (
    fund_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code            VARCHAR2(20)  NOT NULL,
    name            VARCHAR2(100) NOT NULL,
    currency_code   VARCHAR2(3)   NOT NULL,
    balance         NUMBER(16,2)  DEFAULT 0 NOT NULL,
    CONSTRAINT pk_fund          PRIMARY KEY (fund_id),
    CONSTRAINT uq_fund_code     UNIQUE (code),
    CONSTRAINT fk_fund_currency FOREIGN KEY (currency_code) REFERENCES currency (currency_code)
);
COMMENT ON TABLE fund IS 'Company fund(s) from which salaries are paid.';

-- Salary payments (renamed from the old misspelled TRANSECTION table) ----------
CREATE TABLE salary_payment (
    salary_payment_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_id         NUMBER        NOT NULL,
    pay_period_id       NUMBER        NOT NULL,
    payslip_id          NUMBER,
    fund_id             NUMBER,
    amount              NUMBER(14,2)  NOT NULL,
    payment_date        DATE          DEFAULT TRUNC(SYSDATE) NOT NULL,
    method              VARCHAR2(10)  DEFAULT 'BANK' NOT NULL,
    reference           VARCHAR2(60),
    CONSTRAINT pk_salary_payment            PRIMARY KEY (salary_payment_id),
    CONSTRAINT fk_salary_payment_employee   FOREIGN KEY (employee_id)   REFERENCES employee (employee_id),
    CONSTRAINT fk_salary_payment_period     FOREIGN KEY (pay_period_id) REFERENCES pay_period (pay_period_id),
    CONSTRAINT fk_salary_payment_payslip    FOREIGN KEY (payslip_id)    REFERENCES payslip (payslip_id),
    CONSTRAINT fk_salary_payment_fund       FOREIGN KEY (fund_id)       REFERENCES fund (fund_id),
    CONSTRAINT ck_salary_payment_method     CHECK (method IN ('BANK','CASH','CHEQUE')),
    CONSTRAINT ck_salary_payment_amount     CHECK (amount >= 0),
    -- Idempotency: an employee is paid at most once per period (replaces old Check_Valid cursor loop).
    CONSTRAINT uq_salary_payment_emp_period UNIQUE (employee_id, pay_period_id)
);
COMMENT ON TABLE salary_payment IS 'Correctly-spelled replacement for TRANSECTION; one payment per employee per period.';

CREATE INDEX ix_salary_payment_period ON salary_payment (pay_period_id);

-- Leave requests --------------------------------------------------------------
CREATE TABLE leave_request (
    leave_request_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_id         NUMBER        NOT NULL,
    leave_type_id       NUMBER        NOT NULL,
    start_date          DATE          NOT NULL,
    end_date            DATE          NOT NULL,
    days                NUMBER(5,1)   NOT NULL,
    status              VARCHAR2(12)  DEFAULT 'PENDING' NOT NULL,
    reason              VARCHAR2(400),
    CONSTRAINT pk_leave_request         PRIMARY KEY (leave_request_id),
    CONSTRAINT fk_leave_request_emp     FOREIGN KEY (employee_id)   REFERENCES employee (employee_id),
    CONSTRAINT fk_leave_request_type    FOREIGN KEY (leave_type_id) REFERENCES leave_type (leave_type_id),
    CONSTRAINT ck_leave_request_status  CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
    CONSTRAINT ck_leave_request_dates   CHECK (end_date >= start_date),
    CONSTRAINT ck_leave_request_days    CHECK (days >= 0)
);
COMMENT ON TABLE leave_request IS 'Leave records with real dates and typed status; drives loss-of-pay for unpaid leave.';

CREATE INDEX ix_leave_request_emp ON leave_request (employee_id);

-- Loans / advances ------------------------------------------------------------
CREATE TABLE loan (
    loan_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    employee_id     NUMBER        NOT NULL,
    principal       NUMBER(14,2)  NOT NULL,
    outstanding     NUMBER(14,2)  NOT NULL,
    installment     NUMBER(14,2)  NOT NULL,
    start_date      DATE          NOT NULL,
    status          VARCHAR2(10)  DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT pk_loan          PRIMARY KEY (loan_id),
    CONSTRAINT fk_loan_employee FOREIGN KEY (employee_id) REFERENCES employee (employee_id),
    CONSTRAINT ck_loan_status   CHECK (status IN ('ACTIVE','CLOSED')),
    CONSTRAINT ck_loan_amounts  CHECK (principal >= 0 AND outstanding >= 0 AND installment >= 0)
);
COMMENT ON TABLE loan IS 'Employee loans/advances recovered via payroll deductions.';
