--------------------------------------------------------------------------------
-- PaySQL :: V1.4.0 :: Audit & error logging
-- Replaces the old print-only triggers and 'Something wrong happened' handlers.
--------------------------------------------------------------------------------

-- Generic audit trail ---------------------------------------------------------
CREATE TABLE audit_log (
    audit_log_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    table_name      VARCHAR2(60)  NOT NULL,
    action          VARCHAR2(10)  NOT NULL,
    record_id       VARCHAR2(60),
    old_value       CLOB,
    new_value       CLOB,
    changed_by      VARCHAR2(60)  DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    changed_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_log         PRIMARY KEY (audit_log_id),
    CONSTRAINT ck_audit_log_action  CHECK (action IN ('INSERT','UPDATE','DELETE'))
);
COMMENT ON TABLE audit_log IS 'Structured audit trail for sensitive changes (salary, funds, payments).';

-- Application error log --------------------------------------------------------
CREATE TABLE error_log (
    error_log_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    error_code      NUMBER,
    error_message   VARCHAR2(4000),
    backtrace       CLOB,
    module          VARCHAR2(100),
    logged_by       VARCHAR2(60)  DEFAULT SYS_CONTEXT('USERENV','SESSION_USER') NOT NULL,
    logged_at       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_error_log PRIMARY KEY (error_log_id)
);
COMMENT ON TABLE error_log IS 'Captured exceptions with context; replaces swallowed generic error messages.';
